language: python
python:
    - "2.7"
before_install:
    - pip install pytest pytest-cov
    - pip install coveralls
script:
    - py.test --cov-report term-missing --cov acli
after_success:
    coveralls
