language: python
python:
  - "3.4"
  - "3.3"
  - "2.7"
  - "pypy"
before_install:
  - pip install pytest pytest-cov
  - pip install coveralls
install:
  - pip install .
script:
  - py.test --cov-report term-missing --cov acli
after_success:
  coveralls
